
networks:
  rsshub-net:
    driver: bridge

services:
  rsshub:
    container_name: rsshub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env   
    depends_on:
      RSSHubDB:
        condition: service_healthy
    networks:
      - rsshub-net


  RSSHubDB:
    image: postgres:16.3
    container_name: RSSHubDB
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql_isready -U ${DB_USER} -d ${DB_NAME} "]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - rsshub-net

